FROM oven/bun:1.0.25 AS builder

WORKDIR /app
COPY . .

ENV NODE_ENV=production
RUN bun install
RUN bun run build-only

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
