services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  backend:
    build: ./backend
    environment:
      - Flask_ENV=production
      - Flask_APP=app.py
      - DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@db:5432/$DB_NAME
    depends_on:
      - db
    networks:
      - backend
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - frontend

volumes:
  postgres-data:

networks:
  backend:
  frontend:
      